"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import Link from "next/link";

export default function ProjectCard({ project, index }) {
  const [isHovered, setIsHovered] = useState(false);
  const [galleryIndex, setGalleryIndex] = useState(0);
  const [showGallery, setShowGallery] = useState(false);
  const [galleryLoaded, setGalleryLoaded] = useState(false);

  const cardRef = useRef(null);
  const hoverTimerRef = useRef(null);
  const galleryTimerRef = useRef(null);

  const touchActiveRef = useRef(false);
  const touchJustActivatedRef = useRef(false);

  const hasGallery =
    Array.isArray(project.gallery) &&
    project.gallery.length > 0;

  const totalGalleryImages = hasGallery
    ? project.gallery.length
    : 0;

  /*
   * ---------------------------------------------------------
   * CLEAR TIMERS
   * ---------------------------------------------------------
   */

  const clearGalleryTimer = useCallback(() => {
    if (galleryTimerRef.current) {
      clearTimeout(galleryTimerRef.current);
      galleryTimerRef.current = null;
    }
  }, []);

  const clearHoverTimer = useCallback(() => {
    if (hoverTimerRef.current) {
      clearTimeout(hoverTimerRef.current);
      hoverTimerRef.current = null;
    }
  }, []);

  /*
   * ---------------------------------------------------------
   * LOAD GALLERY
   *
   * Gallery images only enter the DOM after activation.
   * This prevents every project gallery loading on page load.
   * ---------------------------------------------------------
   */

  const loadGallery = useCallback(() => {
    if (!hasGallery) return;

    setGalleryLoaded(true);
    setShowGallery(true);
    setGalleryIndex(0);
  }, [hasGallery]);

  /*
   * ---------------------------------------------------------
   * GALLERY LOOP
   * ---------------------------------------------------------
   */

  const scheduleNextImage = useCallback(() => {
    clearGalleryTimer();

    if (!hasGallery || totalGalleryImages <= 1) {
      return;
    }

    galleryTimerRef.current = setTimeout(() => {
      setGalleryIndex((current) => {
        return (current + 1) % totalGalleryImages;
      });

      scheduleNextImage();
    }, 2200);
  }, [
    hasGallery,
    totalGalleryImages,
    clearGalleryTimer,
  ]);

  /*
   * ---------------------------------------------------------
   * START GALLERY
   * ---------------------------------------------------------
   */

  const startGalleryCycle = useCallback(() => {
    if (!hasGallery) return;

    clearGalleryTimer();

    loadGallery();

    scheduleNextImage();
  }, [
    hasGallery,
    clearGalleryTimer,
    loadGallery,
    scheduleNextImage,
  ]);

  /*
   * ---------------------------------------------------------
   * STOP GALLERY
   * ---------------------------------------------------------
   */

  const stopGalleryCycle = useCallback(
    (resetImage = true) => {
      clearGalleryTimer();
      clearHoverTimer();

      setShowGallery(false);

      if (resetImage) {
        setGalleryIndex(0);
      }

      /*
       * IMPORTANT:
       *
       * We do NOT set galleryLoaded(false).
       *
       * Once this card has loaded its gallery,
       * the browser can reuse those images if
       * the user activates it again.
       */
    },
    [
      clearGalleryTimer,
      clearHoverTimer,
    ]
  );

  /*
   * ---------------------------------------------------------
   * DESKTOP HOVER
   * ---------------------------------------------------------
   */

  const handleMouseEnter = () => {
    /*
     * Ignore mouse events generated by touch devices.
     */
    if (touchActiveRef.current) {
      return;
    }

    setIsHovered(true);

    clearHoverTimer();

    /*
     * Wait before loading gallery.
     */
    hoverTimerRef.current = setTimeout(() => {
      startGalleryCycle();
    }, 500);
  };

  const handleMouseLeave = () => {
    /*
     * Do not close while a finger is touching.
     */
    if (touchActiveRef.current) {
      return;
    }

    setIsHovered(false);

    stopGalleryCycle(true);
  };

  /*
   * ---------------------------------------------------------
   * TOUCH / PHONE
   *
   * FIRST TAP:
   * activate card + load gallery
   *
   * SECOND TAP:
   * navigate
   * ---------------------------------------------------------
   */

  const handlePointerDown = (event) => {
    if (event.pointerType !== "touch") {
      return;
    }

    /*
     * FIRST TAP
     */

    if (!isHovered) {
      event.preventDefault();

      touchActiveRef.current = true;
      touchJustActivatedRef.current = true;

      setIsHovered(true);

      clearHoverTimer();

      /*
       * Same 500ms delay as desktop.
       */
      hoverTimerRef.current = setTimeout(() => {
        startGalleryCycle();
      }, 500);

      /*
       * Prevent the synthetic click from
       * navigating after first tap.
       */
      setTimeout(() => {
        touchJustActivatedRef.current = false;
      }, 400);

      return;
    }

    /*
     * SECOND TAP
     *
     * Card already active.
     * Allow normal Link navigation.
     */

    touchActiveRef.current = true;
  };

  /*
   * ---------------------------------------------------------
   * TOUCH RELEASE
   * ---------------------------------------------------------
   */

  const handlePointerUp = (event) => {
    if (event.pointerType !== "touch") {
      return;
    }

    /*
     * Don't immediately deactivate here.
     *
     * This prevents the mobile card from
     * disappearing after the first tap.
     */
    touchActiveRef.current = false;
  };

  const handlePointerCancel = (event) => {
    if (event.pointerType !== "touch") {
      return;
    }

    touchActiveRef.current = false;
  };

  /*
   * ---------------------------------------------------------
   * CLICK
   * ---------------------------------------------------------
   */

  const handleClick = (event) => {
    /*
     * First tap activates only.
     */
    if (touchJustActivatedRef.current) {
      event.preventDefault();
      return;
    }

    /*
     * Second tap navigates normally.
     */
  };

  /*
   * ---------------------------------------------------------
   * TAP OUTSIDE
   * ---------------------------------------------------------
   */

  useEffect(() => {
    const handleDocumentPointerDown = (event) => {
      if (event.pointerType !== "touch") {
        return;
      }

      if (
        cardRef.current &&
        !cardRef.current.contains(event.target)
      ) {
        touchActiveRef.current = false;
        touchJustActivatedRef.current = false;

        setIsHovered(false);

        stopGalleryCycle(true);
      }
    };

    document.addEventListener(
      "pointerdown",
      handleDocumentPointerDown
    );

    return () => {
      document.removeEventListener(
        "pointerdown",
        handleDocumentPointerDown
      );
    };
  }, [stopGalleryCycle]);

  /*
   * ---------------------------------------------------------
   * CLEANUP
   * ---------------------------------------------------------
   */

  useEffect(() => {
    return () => {
      clearGalleryTimer();
      clearHoverTimer();
    };
  }, [
    clearGalleryTimer,
    clearHoverTimer,
  ]);

  /*
   * ---------------------------------------------------------
   * ENTRANCE
   * ---------------------------------------------------------
   */

  const entranceDelay = index * 80;

  return (
    <Link
      ref={cardRef}
      href={`/work/${project.id}`}
      className="project-card"

      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}

      onPointerDown={handlePointerDown}
      onPointerUp={handlePointerUp}
      onPointerCancel={handlePointerCancel}

      onClick={handleClick}

      style={{
        position: "relative",
        display: "block",

        borderRadius: "6px",
        overflow: "hidden",

        background: "#0a0a0a",

        textDecoration: "none",
        color: "inherit",

        opacity: 0,

        transform: isHovered
          ? "translateY(-3px)"
          : "translateY(30px)",

        animation: `
          cardEnter
          0.7s
          cubic-bezier(0.22, 1, 0.36, 1)
          ${entranceDelay}ms
          forwards
        `,

        transition:
          "transform 0.6s cubic-bezier(0.22, 1, 0.36, 1)",

        WebkitTapHighlightColor: "transparent",

        touchAction: "manipulation",
      }}
    >

      {/* IMAGE CONTAINER */}

      <div
        style={{
          position: "relative",
          width: "100%",
          aspectRatio: "16 / 10",
          overflow: "hidden",
          background: "#111",
        }}
      >

        {/* ------------------------------------------------
            COVER IMAGE
        ------------------------------------------------ */}

        <img
          src={
            project.coverImage ||
            "/works/placeholder.jpg"
          }
          alt={project.title}
          draggable="false"
          style={{
            position: "absolute",
            inset: 0,

            width: "100%",
            height: "100%",

            objectFit: "cover",

            transform: isHovered
              ? "scale(1.06)"
              : "scale(1)",

            filter: isHovered
              ? "brightness(0.35)"
              : "brightness(1)",

            transition:
              "transform 1.2s cubic-bezier(0.22, 1, 0.36, 1), filter 0.8s ease",

            zIndex: 0,
          }}
        />

        {/* ------------------------------------------------
            LAZY GALLERY

            IMPORTANT:

            project.gallery is NOT rendered until
            galleryLoaded === true.

            Therefore gallery images don't load
            for every card when the page opens.
        ------------------------------------------------ */}

        {hasGallery && galleryLoaded && (
          <>
            {project.gallery.map((img, i) => {
              const isCurrent =
                i === galleryIndex;

              return (
                <img
                  key={`${img}-${i}`}
                  src={img}
                  alt={`${project.title} ${i + 1}`}
                  draggable="false"
                  loading="lazy"
                  decoding="async"

                  style={{
                    position: "absolute",
                    inset: 0,

                    width: "100%",
                    height: "100%",

                    objectFit: "cover",

                    opacity:
                      showGallery && isCurrent
                        ? 1
                        : 0,

                    transform:
                      showGallery
                        ? "scale(1.06)"
                        : "scale(1.03)",

                    filter:
                      "brightness(0.35)",

                    transition:
                      "opacity 1.2s cubic-bezier(0.4, 0, 0.2, 1), transform 2.2s cubic-bezier(0.22, 1, 0.36, 1)",

                    pointerEvents:
                      "none",

                    zIndex:
                      isCurrent ? 2 : 1,
                  }}
                />
              );
            })}
          </>
        )}

        {/* ------------------------------------------------
            DARK OVERLAY
        ------------------------------------------------ */}

        <div
          style={{
            position: "absolute",
            inset: 0,

            background:
              "linear-gradient(180deg, rgba(0,0,0,0) 25%, rgba(0,0,0,0.72) 100%)",

            opacity:
              isHovered ? 1 : 0,

            transition:
              "opacity 0.7s ease",

            pointerEvents:
              "none",

            zIndex: 3,
          }}
        />

        {/* ------------------------------------------------
            CONTENT
        ------------------------------------------------ */}

        <div
          style={{
            position: "absolute",
            inset: 0,

            display: "flex",
            flexDirection: "column",
            justifyContent: "flex-end",

            padding: "1.5rem",

            zIndex: 5,

            opacity:
              isHovered ? 1 : 0,

            transform:
              isHovered
                ? "translateY(0)"
                : "translateY(12px)",

            transition:
              "opacity 0.5s ease, transform 0.6s cubic-bezier(0.22, 1, 0.36, 1)",

            pointerEvents:
              "none",
          }}
        >

          {/* CATEGORY / YEAR */}

          <div
            style={{
              display: "flex",
              alignItems: "center",

              gap: "0.6rem",

              marginBottom: "0.5rem",

              opacity:
                isHovered ? 1 : 0,

              transform:
                isHovered
                  ? "translateY(0)"
                  : "translateY(8px)",

              transition:
                "opacity 0.4s ease 0.1s, transform 0.5s cubic-bezier(0.22, 1, 0.36, 1) 0.1s",
            }}
          >
            <span
              style={{
                fontSize: "0.65rem",
                letterSpacing: "0.12em",
                textTransform: "uppercase",

                color:
                  "rgba(232,230,227,0.7)",
              }}
            >
              {project.category}
            </span>

            <span
              style={{
                color:
                  "rgba(232,230,227,0.3)",

                fontSize: "0.6rem",
              }}
            >
              •
            </span>

            <span
              style={{
                fontSize: "0.65rem",
                letterSpacing: "0.08em",

                color:
                  "rgba(232,230,227,0.5)",
              }}
            >
              {project.year}
            </span>
          </div>

          {/* TITLE */}

          <h3
            style={{
              fontSize:
                "clamp(1.1rem, 2vw, 1.5rem)",

              fontWeight: 400,

              lineHeight: 1.15,

              margin: 0,

              color: "#e8e6e3",

              opacity:
                isHovered ? 1 : 0,

              transform:
                isHovered
                  ? "translateY(0)"
                  : "translateY(10px)",

              transition:
                "opacity 0.45s ease 0.15s, transform 0.55s cubic-bezier(0.22, 1, 0.36, 1) 0.15s",
            }}
          >
            {project.title}
          </h3>

          {/* LOCATION */}

          {project.location && (
            <div
              style={{
                display: "flex",
                alignItems: "center",

                gap: "0.4rem",

                marginTop: "0.6rem",

                opacity:
                  isHovered ? 1 : 0,

                transform:
                  isHovered
                    ? "translateY(0)"
                    : "translateY(8px)",

                transition:
                  "opacity 0.4s ease 0.25s, transform 0.5s cubic-bezier(0.22, 1, 0.36, 1) 0.25s",
              }}
            >
              <svg
                width="12"
                height="12"
                viewBox="0 0 24 24"
                fill="none"
                stroke="rgba(232,230,227,0.5)"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z" />
                <circle
                  cx="12"
                  cy="10"
                  r="3"
                />
              </svg>

              <span
                style={{
                  fontSize: "0.75rem",

                  color:
                    "rgba(232,230,227,0.55)",

                  letterSpacing:
                    "0.02em",
                }}
              >
                {project.location}
              </span>
            </div>
          )}

          {/* SERVICES */}

          {Array.isArray(project.services) &&
            project.services.length > 0 && (
              <div
                style={{
                  display: "flex",
                  flexWrap: "wrap",

                  gap: "0.35rem",

                  marginTop: "0.7rem",

                  opacity:
                    isHovered ? 1 : 0,

                  transform:
                    isHovered
                      ? "translateY(0)"
                      : "translateY(6px)",

                  transition:
                    "opacity 0.35s ease 0.35s, transform 0.45s cubic-bezier(0.22, 1, 0.36, 1) 0.35s",
                }}
              >
                {project.services
                  .slice(0, 3)
                  .map((svc, i) => (
                    <span
                      key={i}
                      style={{
                        fontSize: "0.6rem",

                        letterSpacing:
                          "0.06em",

                        textTransform:
                          "uppercase",

                        color:
                          "rgba(232,230,227,0.45)",

                        padding:
                          "0.2rem 0.5rem",

                        border:
                          "1px solid rgba(232,230,227,0.12)",

                        borderRadius: "3px",
                      }}
                    >
                      {svc}
                    </span>
                  ))}

                {project.services.length >
                  3 && (
                  <span
                    style={{
                      fontSize: "0.6rem",

                      color:
                        "rgba(232,230,227,0.3)",

                      padding:
                        "0.2rem 0",
                    }}
                  >
                    +
                    {project.services.length -
                      3}
                  </span>
                )}
              </div>
            )}

          {/* GALLERY INDICATOR */}

          {hasGallery &&
            totalGalleryImages > 1 && (
              <div
                style={{
                  display: "flex",
                  alignItems: "center",

                  gap: "0.35rem",

                  height: "0.7rem",
                  minHeight: "0.7rem",

                  marginTop: "0.9rem",

                  overflow: "hidden",

                  opacity:
                    isHovered ? 1 : 0,

                  transition:
                    "opacity 0.3s ease 0.4s",
                }}
              >
                {project.gallery.map(
                  (_, i) => (
                    <span
                      key={i}
                      style={{
                        flexShrink: 0,

                        width:
                          i === galleryIndex
                            ? "1.2rem"
                            : "0.35rem",

                        height:
                          "0.35rem",

                        borderRadius:
                          "999px",

                        background:
                          i === galleryIndex
                            ? "rgba(232,230,227,0.9)"
                            : "rgba(232,230,227,0.25)",

                        transition:
                          "width 0.4s ease, background 0.4s ease",
                      }}
                    />
                  )
                )}
              </div>
            )}
        </div>

        {/* ------------------------------------------------
            MOBILE ACTIVATION INDICATOR
        ------------------------------------------------ */}

        {hasGallery &&
          totalGalleryImages > 1 &&
          !isHovered && (
            <div
              style={{
                position: "absolute",

                right: "1rem",
                bottom: "1rem",

                width: "24px",
                height: "24px",

                border:
                  "1px solid rgba(232,230,227,0.25)",

                borderRadius: "50%",

                display: "flex",

                alignItems: "center",
                justifyContent: "center",

                opacity: 0.6,

                zIndex: 10,

                pointerEvents: "none",
              }}
            >
              <span
                style={{
                  width: "5px",
                  height: "5px",

                  borderRadius: "50%",

                  background:
                    "rgba(232,230,227,0.65)",
                }}
              />
            </div>
          )}

      </div>
    </Link>
  );
}